import type { Metadata } from "next";
import "./globals.css";

let geistSans: any = { variable: "" };
let geistMono: any = { variable: "" };

try {
  const { Geist, Geist_Mono } = require("next/font/google");
  geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  });

  geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  });
} catch (e) {
  // Fallback if Google Fonts are unavailable
  console.warn("Google Fonts unavailable, using fallback");
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
